import type { Ending } from '../game/types';

/**
 * The four endings (spec s.7 Act VI, s.8).
 *
 * C - "record something new" - is the intended solution, and the only one that
 * resolves the question the whole game is asking (spec s.44): memories only
 * matter because they are memories. Destroying the past and preserving it are
 * both refusals to let anything change.
 */
export const ENDINGS: Record<string, Ending> = {
  record: {
    id: 'record',
    title: 'ONE MORE CREDIT',
    script: [
      ['stopmusic'],
      ['caption', 'Jack takes the blank cassette out of his pocket.'],
      ['jack', 'It wants a memory of whoever is operating it.'],
      ['say', 'arthur', 'Yes.'],
      ['jack', 'Then it can have one. Just not the one you had in mind.'],
      ['wait', 0.5],
      ['sfx', 'cassette'],
      ['caption', 'He does not record the town as it is.'],
      ['wait', 0.6],
      ['caption', 'He records everyone in it. Arthur. Maggie. Derek. Kevin. Brenda.'],
      ['wait', 0.5],
      ['caption', 'The machines. The seafront. The whole ridiculous evening.'],
      ['wait', 0.6],
      ['jack', 'Not a perfect day. Just a real one.'],
      ['wait', 0.5],
      ['sfx', 'button'],
      ['caption', 'RECORD'],
      ['shake', 1],
      ['sfx', 'powerdown'],
      ['wait', 0.4],
      ['card', 'EVERYTHING GOES WHITE.'],
      ['fade', 'out', 1.2],
      ['music', 'ending'],
      ['card', 'SATURDAY 19 SEPTEMBER 1987', '07:12'],
      ['fade', 'in', 1.2],
      ['caption', 'Jack wakes up on the arcade floor. The building is still standing.'],
      ['wait', 0.5],
      ['say', 'arthur', 'Morning.'],
      ['jack', 'What happened?'],
      ['say', 'arthur', 'Nothing.'],
      ['jack', 'Nothing?'],
      ['say', 'arthur', 'Nothing unusual.'],
      ['wait', 0.5],
      ['caption', 'The demolition has been cancelled. A planning error, discovered overnight.'],
      ['wait', 0.6],
      ['caption', 'The unmarked machine is switched off. Jack walks past it.'],
      ['wait', 0.8],
      ['sfx', 'credit'],
      ['caption', 'CREDIT 1'],
      ['wait', 0.6],
      ['caption', 'He stops. He smiles. He puts in a coin.'],
      ['wait', 0.6],
      ['caption', 'THANK YOU, JACK.'],
      ['wait', 0.7],
      ['jack', 'Oh, come on.'],
      ['fade', 'out', 1.5],
    ],
  },

  destroy: {
    id: 'destroy',
    title: 'A TECHNICALLY CORRECT SOLUTION',
    script: [
      ['stopmusic'],
      ['caption', 'Jack picks up the bolt cutters.'],
      ['say', 'arthur', 'Jack. Please.'],
      ['jack', 'Sorry, Arthur.'],
      ['sfx', 'zap'],
      ['shake', 1],
      ['sfx', 'powerdown'],
      ['wait', 0.5],
      ['caption', 'The machine dies with a noise like a held breath being let go.'],
      ['wait', 0.6],
      ['caption', 'Every clock in Brighton Vale moves to eighteen minutes past eleven.'],
      ['wait', 0.6],
      ['caption', 'Thirteen years late, and all at once.'],
      ['fade', 'out', 1.2],
      ['music', 'ending'],
      ['card', 'SATURDAY 19 SEPTEMBER 1987', '09:43'],
      ['fade', 'in', 1],
      ['caption', 'The bulldozer arrives on time.'],
      ['wait', 0.8],
      ['caption', 'Arthur watches from across the road and does not say anything at all.'],
      ['wait', 0.8],
      ['jack', 'Well. Technically I solved the problem.'],
      ['wait', 0.8],
      ['caption', 'Nobody has ever found out what happened to Elliot Vale.'],
      ['fade', 'out', 1.5],
    ],
  },

  preserve: {
    id: 'preserve',
    title: 'FRIDAY',
    script: [
      ['stopmusic'],
      ['caption', 'Jack steps back from the machine.'],
      ['jack', 'All right. Keep it.'],
      ['say', 'arthur', 'Thank you.'],
      ['wait', 0.5],
      ['sfx', 'powerup'],
      ['shake', 0.8],
      ['caption', 'The Memory Master locks onto Friday and holds it there.'],
      ['wait', 0.7],
      ['fade', 'out', 1.5],
      ['card', 'FRIDAY 18 SEPTEMBER 1987', '19:00'],
      ['wait', 0.5],
      ['caption', 'The arcade is open. Machines everywhere. Music. Flashing lights.'],
      ['wait', 0.6],
      ['say', 'arthur', "You're late."],
      ['jack', "It's seven o'clock."],
      ['say', 'arthur', 'Exactly.'],
      ['wait', 0.6],
      ['jack', '...'],
      ['wait', 0.8],
      ['jack', 'We have done this.'],
      ['wait', 0.6],
      ['say', 'arthur', 'We are always going to have done this.'],
      ['wait', 0.8],
      ['caption', 'Nothing in Brighton Vale will ever change again.'],
      ['wait', 0.6],
      ['caption', 'Which was, after all, the point.'],
      ['fade', 'out', 1.5],
    ],
  },

  secret: {
    id: 'secret',
    title: 'SOME THINGS SHOULD NOT BE FORGOTTEN',
    script: [
      ['stopmusic'],
      ['caption', 'Jack loads every cassette he has found into the machine at once.'],
      ['wait', 0.6],
      ['sfx', 'rewind'],
      ['sfx', 'relay'],
      ['wait', 0.5],
      ['vision', 'vale_reveal'],
      ['say', 'vale', 'Hello, Margaret.'],
      ['wait', 0.8],
      ['caption', 'It is not a recording answering a question. It is an answer that has been waiting.'],
      ['wait', 0.6],
      ['say', 'vale', 'I need you to know that I was not careless, and I did not leave.'],
      ['wait', 0.5],
      ['say', 'vale', 'It could hold a person, if a person stayed. So I stayed.'],
      ['say', 'vale', 'Because the alternative was that one day you would not be able to remember my voice.'],
      ['wait', 0.8],
      ['say', 'arthur', 'He made me promise not to tell you.'],
      ['say', 'arthur', 'I have regretted it every single day since, and I kept it anyway.'],
      ['wait', 0.8],
      ['music', 'ending'],
      ['caption', 'Maggie sits down on the concrete floor and listens to the whole tape.'],
      ['wait', 1.2],
      ['caption', 'Nobody says anything for a long time.'],
      ['wait', 1.4],
      ['jack', 'You alright?'],
      ['wait', 1.0],
      ['say', 'maggie', 'No.'],
      ['wait', 1.0],
      ['jack', 'Fair enough.'],
      ['wait', 1.2],
      ['fade', 'out', 1.5],
      ['card', 'SATURDAY 19 SEPTEMBER 1987'],
      ['fade', 'in', 1],
      ['caption', 'The arcade is still standing. The demolition was cancelled.'],
      ['wait', 0.6],
      ['caption', 'Maggie keeps the tape. She does not play it again for a very long time.'],
      ['wait', 0.8],
      ['caption', 'But she knows exactly where it is.'],
      ['fade', 'out', 1.5],
    ],
  },
};
